//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystemFrontend
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookCopies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookCopies()
        {
            this.Loans = new HashSet<Loans>();
        }
    
        public int CopyID { get; set; }
        public int BookID { get; set; }
        public string BookShelf { get; set; }
        public int Shelf { get; set; }
        public int ShelfPosition { get; set; }
        public string CopyStatus { get; set; }
    
        public virtual Books Books { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loans> Loans { get; set; }
    }
}
