//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystemFrontend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loans
    {
        public int LoanID { get; set; }
        public int CopyID { get; set; }
        public int BookID { get; set; }
        public int BorrowerID { get; set; }
        public System.DateTime LoanDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
    
        public virtual BookCopies BookCopies { get; set; }
        public virtual Books Books { get; set; }
        public virtual Borrowers Borrowers { get; set; }
    }
}
